"""Read the saved bundle and forecast without fitting models or accessing MySQL."""

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from script.common import DEFAULT_MODEL_PATH, GROUPS, METHODS, add_sales_features, compare_forecasts, predict_models


def records(frame):
    """Convert pandas dates/numbers and missing values to valid JSON values."""
    return json.loads(frame.to_json(orient="records", date_format="iso"))


class ForecastPredictor:
    def __init__(self, model_path=DEFAULT_MODEL_PATH):
        # Only load trusted local artifacts generated by script.train.
        bundle = joblib.load(Path(model_path))
        self.metadata = bundle["metadata"]
        if self.metadata.get("schema_version") != 1:
            raise ValueError("Unsupported model bundle. Retrain with the current training script.")
        self.history = bundle["history"]
        self.preprocessor = bundle["preprocessor"]
        self.models = bundle["models"]
        self.validation = bundle["validation_predictions"]
        self.test = bundle["test_predictions"]
        self.stores = self.history[["store_id", "store_name"]].drop_duplicates().sort_values("store_id")
        self.categories = self.history[["category_id", "category_name"]].drop_duplicates().sort_values("category_id")

    def select(self, frame, store_id=None, category_id=None):
        if store_id is not None and store_id not in self.stores.store_id.values:
            raise ValueError("Unknown store ID.")
        if category_id is not None and category_id not in self.categories.category_id.values:
            raise ValueError("Unknown category ID.")
        selected = frame
        if store_id is not None:
            selected = selected[selected.store_id == store_id]
        if category_id is not None:
            selected = selected[selected.category_id == category_id]
        return selected.copy()

    def model_info(self):
        return {**self.metadata, "stores": records(self.stores), "categories": records(self.categories)}

    def forecast(self, month=None, store_id=None, category_id=None):
        expected_month = pd.Timestamp(self.metadata["forecast_month"])
        requested_month = pd.Timestamp(month) if month else expected_month
        if requested_month != expected_month:
            raise ValueError(f"Only {expected_month:%Y-%m-%d} is supported by this data snapshot.")

        # Unknown future targets stay missing. Features use earlier observed sales only.
        next_rows = self.history[GROUPS + ["store_name", "category_name"]].drop_duplicates().copy()
        next_rows["month_start"] = expected_month
        next_rows["units_sold"] = np.nan
        full_data = add_sales_features(pd.concat([self.history, next_rows], ignore_index=True))
        future = full_data[full_data.month_start == expected_month]
        predictions = predict_models(self.preprocessor, self.models, future)
        predictions = self.select(predictions, store_id, category_id)
        selected_model = self.metadata["selected_model"]
        predictions["prediction"] = predictions[selected_model]
        predictions = predictions.drop(columns="units_sold")

        historical = self.select(self.history, store_id, category_id)
        history_totals = historical.groupby("month_start", as_index=False).units_sold.sum().tail(12)
        total = float(predictions.prediction.sum())
        last_month = float(predictions["Last month"].sum())
        return {
            "model_version": self.metadata["model_version"], "model": selected_model,
            "forecast_month": expected_month.strftime("%Y-%m-%d"),
            "store_id": store_id, "category_id": category_id,
            "summary": {
                "forecast_units": total, "last_month_units": last_month,
                "three_month_average": float(predictions["3-month average"].sum()),
                "change_units": total - last_month,
                "change_pct": (total / last_month - 1) * 100 if last_month else None,
                "series_count": len(predictions),
            },
            "rows": records(predictions), "history": records(history_totals),
        }

    def performance(self, period="test", store_id=None, category_id=None):
        if period not in {"test", "validation"}:
            raise ValueError("Period must be test or validation.")
        data = self.select(self.test if period == "test" else self.validation, store_id, category_id)
        scores = compare_forecasts(data)
        selected_model = self.metadata["selected_model"]
        errors = data.copy()
        errors["error"] = errors[selected_model] - errors.units_sold
        errors["absolute_error"] = errors.error.abs()
        groups = {}
        for level, columns in {
            "stores": ["store_id", "store_name"],
            "categories": ["category_id", "category_name"],
            "series": ["store_id", "store_name", "category_id", "category_name"],
        }.items():
            table = errors.groupby(columns, as_index=False).agg(
                mae=("absolute_error", "mean"), bias=("error", "mean")
            )
            groups[level] = records(table.sort_values("mae", ascending=False))
        monthly = data.groupby("month_start", as_index=False)[["units_sold"] + METHODS].sum()
        return {"period": period, "selected_model": selected_model,
                "period_label": self.metadata[f"{period}_period"],
                "scores": records(scores), "monthly": records(monthly),
                "errors": groups, "predictions": records(data)}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-path", type=Path, default=DEFAULT_MODEL_PATH)
    parser.add_argument("--month", help="YYYY-MM-01; defaults to the next supported month.")
    parser.add_argument("--store-id", type=int)
    parser.add_argument("--category-id", type=int)
    args = parser.parse_args()
    predictor = ForecastPredictor(args.model_path)
    result = predictor.forecast(args.month, args.store_id, args.category_id)
    print(json.dumps(result, indent=2, allow_nan=False))
